
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
    themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# http:
#   ssl_certificate: /config/certs/fullchain.pem
#   ssl_key: /config/certs/privkey.pem

spotify:
    client_id: !secret SPOTIFY_CLIENT_ID
    client_secret: !secret SPOTIFY_CLIENT_SECRET

recorder:
    purge_keep_days: 2

light:
  - platform: switch
    name: Dining Table Lights
    entity_id: switch.dining_table_lights
  - platform: switch
    name: String Lights
    entity_id: switch.string_lights
  - platform: group
    name: Studio Lights
    entities:
      - light.bed_color_lamp_4
      - light.desk_color_lamp_1
      - light.desk_white_lamp_1
      - light.desk_white_lamp_2
      - light.string_lights
      - light.dining_table_lights
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
  - platform: group
    name: Desk Lights
    entities:
      - light.desk_color_lamp_1
      - light.desk_white_lamp_1
      - light.desk_white_lamp_2
  - platform: group
    name: TV Lights
    entities:
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3

homeassistant:
    media_dirs:
        local: /config/media

camera:
  - platform: mjpeg
    mjpeg_url: http://10.0.0.161:8081/cam_pic_new.php
    username: "picam"
    password: "opensesame"
    name: "Window"

sensor:
  - platform: scrape
    resource: http://10.0.0.161:1111/noise.html
    select: "span"
    name: "AC Noise"
  - platform: template
    sensors:
      ac_noise_bool:
        name: "AC Noise (Boolean)"
        value_template: "{{ states('sensor.ac_noise') | float > 1.5 }}"
