- id: '1610994719610'
  name: Theater Mode
  entities:
    light.dining_table_lights:
      supported_color_modes:
      - onoff
      friendly_name: Dining Table Lights
      supported_features: 0
      state: 'off'
    light.string_lights:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: String Lights
      supported_features: 0
      state: 'on'
    light.tv_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 26
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      entity_id:
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
      friendly_name: TV Lights
      icon: mdi:lightbulb-group
      supported_features: 44
      state: 'on'
    light.bed_color_lamp_4:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 26
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      friendly_name: Bed color lamp 4
      supported_features: 63
      state: 'on'
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      friendly_name: Sync What's Playing to Lights?
      icon: mdi:palette
      state: 'off'
    light.desk_white_lamp_1:
      supported_color_modes:
      - brightness
      friendly_name: Desk white lamp 1
      supported_features: 41
      state: 'off'
    light.desk_white_lamp_2:
      supported_color_modes:
      - brightness
      friendly_name: Desk white lamp 2
      supported_features: 41
      state: 'off'
    light.desk_color_lamp_1:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 26
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      friendly_name: Desk color lamp 1
      supported_features: 63
      state: 'on'
  icon: mdi:filmstrip
- id: '1610994765804'
  name: Full On
  entities:
    light.studio_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - random
      - colorloop
      brightness: 255
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.45
      - 0.406
      effect: none
      entity_id:
      - light.bed_color_lamp_4
      - light.desk_color_lamp_1
      - light.desk_white_lamp_1
      - light.desk_white_lamp_2
      - light.string_lights
      - light.dining_table_lights
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
      friendly_name: Studio Lights
      icon: mdi:lightbulb-group
      supported_features: 63
      state: 'on'
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      friendly_name: Sync What's Playing to Lights?
      icon: mdi:palette
      state: 'off'
  icon: mdi:lightbulb-on-outline
- id: '1610994787395'
  name: Full Off
  entities:
    light.studio_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - random
      - colorloop
      entity_id:
      - light.bed_color_lamp_4
      - light.desk_color_lamp_1
      - light.desk_white_lamp_1
      - light.desk_white_lamp_2
      - light.string_lights
      - light.dining_table_lights
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
      friendly_name: Studio Lights
      icon: mdi:lightbulb-group
      supported_features: 63
      state: 'off'
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      friendly_name: Sync What's Playing to Lights?
      icon: mdi:palette
      state: 'off'
  icon: mdi:lightbulb-off-outline
- id: '1610994850307'
  name: Daytime Work
  entities:
    light.desk_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - random
      - colorloop
      brightness: 234
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.45
      - 0.406
      effect: none
      entity_id:
      - light.desk_color_lamp_1
      - light.desk_white_lamp_1
      - light.desk_white_lamp_2
      friendly_name: Desk Lights
      icon: mdi:lightbulb-group
      supported_features: 63
      state: 'on'
    light.bed_color_lamp_4:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      friendly_name: Bed color lamp 4
      supported_features: 63
      state: 'off'
    light.string_lights:
      friendly_name: String Lights
      supported_features: 0
      state: 'off'
    light.tv_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - random
      - colorloop
      entity_id:
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
      friendly_name: TV Lights
      icon: mdi:lightbulb-group
      supported_features: 63
      state: 'off'
    light.dining_table_lights:
      friendly_name: Dining Table Lights
      supported_features: 0
      state: 'off'
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      friendly_name: Sync What's Playing to Lights?
      icon: mdi:palette
      state: 'off'
  icon: mdi:briefcase-outline
- id: '1619984401301'
  name: Party
  entities:
    light.bed_color_lamp_4:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 255
      hs_color:
      - 229.859
      - 27.843
      rgb_color:
      - 184
      - 196
      - 255
      xy_color:
      - 0.264
      - 0.258
      effect: none
      friendly_name: Bed color lamp 4
      supported_features: 63
      state: 'on'
    light.desk_color_lamp_1:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 255
      hs_color:
      - 220.435
      - 36.078
      rgb_color:
      - 163
      - 193
      - 255
      xy_color:
      - 0.241
      - 0.251
      effect: none
      friendly_name: Desk color lamp 1
      supported_features: 63
      state: 'on'
    light.desk_white_lamp_1:
      friendly_name: Desk white lamp 1
      supported_features: 41
      state: 'off'
    light.desk_white_lamp_2:
      friendly_name: Desk white lamp 2
      supported_features: 41
      state: 'off'
    switch.dining_table_lights:
      friendly_name: 'Dining Table Lights '
      state: 'off'
    light.tv_color_lamp_2:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 255
      hs_color:
      - 228.791
      - 35.686
      rgb_color:
      - 164
      - 181
      - 255
      xy_color:
      - 0.245
      - 0.236
      effect: none
      friendly_name: TV color lamp 2
      supported_features: 63
      state: 'on'
    light.tv_color_lamp_3:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 255
      hs_color:
      - 339.871
      - 60.784
      rgb_color:
      - 255
      - 100
      - 152
      xy_color:
      - 0.511
      - 0.267
      effect: none
      friendly_name: TV color lamp 3
      supported_features: 63
      state: 'on'
    switch.string_lights:
      friendly_name: String Lights
      state: unavailable
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      friendly_name: Sync What's Playing to Lights?
      icon: mdi:palette
      state: 'on'
  icon: mdi:cake
- id: '1621908839349'
  name: Relax
  entities:
    automation.toggle_color_sync:
      last_triggered: '2021-05-22T04:44:02.004792+00:00'
      mode: single
      current: 0
      friendly_name: Toggle Color Sync
      state: 'off'
    light.dining_table_lights:
      supported_color_modes:
      - onoff
      friendly_name: Dining Table Lights
      supported_features: 0
      state: 'off'
    light.desk_white_lamp_1:
      supported_color_modes:
      - brightness
      friendly_name: Desk white lamp 1
      supported_features: 41
      state: 'off'
    light.desk_white_lamp_2:
      supported_color_modes:
      - brightness
      friendly_name: Desk white lamp 2
      supported_features: 41
      state: 'off'
    light.desk_color_lamp_1:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 126
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      friendly_name: Desk color lamp 1
      supported_features: 63
      state: 'on'
    light.string_lights:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: String Lights
      supported_features: 0
      state: 'on'
    light.tv_lights:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 126
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      entity_id:
      - light.tv_color_lamp_2
      - light.tv_color_lamp_3
      friendly_name: TV Lights
      icon: mdi:lightbulb-group
      supported_features: 44
      state: 'on'
    light.bed_color_lamp_4:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 126
      hs_color:
      - 39.808
      - 40.784
      rgb_color:
      - 255
      - 220
      - 151
      xy_color:
      - 0.421
      - 0.397
      effect: none
      friendly_name: Bed color lamp 4
      supported_features: 63
      state: 'on'
  icon: mdi:spa
